[tool.poetry]
name = "poetry"
version = "0.1.0"
description = "Aplicação de exemplo usando o princípio do SOLID"
authors = ["taissalissousa@gmail.com"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12"
requests = ">=2.34.2,<3.0.0"
pydantic = {extras = ["email"], version = "^2.13.5"}
fastapi = "^0.141.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
