[project]
name = "poetry"
version = "y"
description = "Aplicação de exemplo usando o principio do SOLID"
authors = [
    {name = "taissalissousa@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "requests (>=2.34.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
